
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 16 09:42:56 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 31;
  public static final int GE = 22;
  public static final int SEMI = 35;
  public static final int LPAREN = 32;
  public static final int REPEAT = 11;
  public static final int FOR = 12;
  public static final int MINUS = 29;
  public static final int WRITE = 15;
  public static final int RPAREN = 33;
  public static final int AND = 26;
  public static final int LT = 23;
  public static final int OR = 27;
  public static final int BEGIN = 10;
  public static final int UNTIL = 13;
  public static final int NUM = 18;
  public static final int PLUS = 28;
  public static final int ASSIGN = 19;
  public static final int IF = 4;
  public static final int ID = 16;
  public static final int LE = 21;
  public static final int EOF = 0;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int VOID = 3;
  public static final int EQ = 20;
  public static final int TIMES = 30;
  public static final int COLOM = 34;
  public static final int ELSE = 8;
  public static final int READ = 14;
  public static final int THEN = 7;
  public static final int VEC = 17;
  public static final int END = 9;
  public static final int DIFF = 25;
  public static final int FALSE = 6;
  public static final int TipoDato = 2;
  public static final int GT = 24;
}

