
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 13 16:28:34 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 28;
  public static final int AND = 24;
  public static final int READ = 12;
  public static final int OVER = 29;
  public static final int LT = 21;
  public static final int ELSE = 6;
  public static final int PLUS = 26;
  public static final int RPAREN = 31;
  public static final int OR = 25;
  public static final int THEN = 5;
  public static final int SEMI = 33;
  public static final int END = 7;
  public static final int TipoDato = 2;
  public static final int IF = 4;
  public static final int LPAREN = 30;
  public static final int GT = 22;
  public static final int COLOM = 32;
  public static final int LE = 19;
  public static final int WRITE = 13;
  public static final int ID = 14;
  public static final int NUM = 16;
  public static final int BEGIN = 8;
  public static final int EOF = 0;
  public static final int VEC = 15;
  public static final int MINUS = 27;
  public static final int GE = 20;
  public static final int error = 1;
  public static final int EQ = 18;
  public static final int ASSIGN = 17;
  public static final int UNTIL = 11;
  public static final int DIFF = 23;
  public static final int FOR = 10;
  public static final int VOID = 3;
  public static final int REPEAT = 9;
}

