
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 13 02:13:47 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 29;
  public static final int AND = 25;
  public static final int READ = 13;
  public static final int OVER = 30;
  public static final int LT = 22;
  public static final int ELSE = 7;
  public static final int PLUS = 27;
  public static final int RPAREN = 32;
  public static final int OR = 26;
  public static final int INT = 2;
  public static final int THEN = 6;
  public static final int SEMI = 34;
  public static final int END = 8;
  public static final int IF = 5;
  public static final int LPAREN = 31;
  public static final int GT = 23;
  public static final int COLOM = 33;
  public static final int LE = 20;
  public static final int WRITE = 14;
  public static final int ID = 15;
  public static final int NUM = 17;
  public static final int BEGIN = 9;
  public static final int BOOLEAN = 3;
  public static final int EOF = 0;
  public static final int VEC = 16;
  public static final int MINUS = 28;
  public static final int GE = 21;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int ASSIGN = 18;
  public static final int UNTIL = 12;
  public static final int DIFF = 24;
  public static final int FOR = 11;
  public static final int VOID = 4;
  public static final int REPEAT = 10;
}

